version: 2.1

jobs:
  docker_compose_tests:
    docker:
      - image: cimg/base:2020.08
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.7'
      - run:
          name: Spin up services with Docker Compose
          command: |
            docker-compose up -d
      - run:
          name: List running containers
          command: |
            docker ps
      - run:
          name: wait for registry to be ready
          command: |
            docker container run --network container:registry jwilder/dockerize \
            -wait http://localhost:8081 -wait-retry-interval 2s -timeout 60s

workflows:
  # Runs services as-per a docker-compose file,
  # and runs integration tests against spun services.
  compose_tests:
    jobs:
      - docker_compose_tests
